name: ${artifactId}
main: ${main}
author: ${author}
version: ${version}
description: ${description}
website: ${website}
loadbefore: [ PickaxeUpgrades ]
softdepend: [ HolographicDisplays, PlaceholderAPI, SuperiorSkyblock2 ]
commands:
  islandmines:
    description: Main Command - IslandMines
    aliases: [ xislandmines, islandmine, imines, imine, mines, mine ]